name: Build and test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  determine-go-version:
    name: "Determine Go version"
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.determine-go-version.outputs.version }}
    steps:
     - uses: actions/checkout@v3
     - name: Determine Go version
       id: determine-go-version
       uses: ./.github/go-version

  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ${{ needs.get-go-version.outputs.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ needs.get-go-version.outputs.go-version }}
      id: go
    - name: checkout
      uses: actions/checkout@v3
    - name: cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

  check:
    name: Check
    runs-on: ubuntu-latest
    needs:
      - determine-go-version
      - setup
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
    

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - determine-go-version
      - setup
    steps:
      - name: build
        run: |
          make build

  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - determine-go-version
      - setup
    steps:
      - name: test
        run: |
          make test
